### ISSUE TITLE
Questions on the microbial_load_predictor model

### ISSUE THREAD

**Issue by kaisir97** [grp-bork/microbial_load_predictor#1]
Microbial load predictor is a great tool for solving the problem we all had in analyzing microbiome data and I really appreciate your idea and work. 

I have a question about the model:
Is the microbioal load predictor in your MLpredictor package trained from Galaxy/Microliver data or Metacardis data?
- I have looked on the model attributes you have provided with RDS file and it seems to be trained on Metacardis dataset since the model$trainingData attribute has 1,812 columns but I wanted to be sure. Also, if it is trained on Metacardis dataset is there any reason not to use the model trained on Galaxy/Microliver data?

**Comment by nishijima-suguru** [comment]
Yes, the model we released was trained on the MetaCardis dataset; we released this model because MetaCardis included more independent individuals (there are some time series samples in the GALAXY/MicrobLiver). But we are now preparing to publish the model trained on the GALAXY dataset as well. Our validation showed that their predictive performances were almost comparable but there might be slight differences depending on the input dataset.
